pub mod channel;
pub mod convert;
pub mod ext;
pub mod macros;
pub mod ops;

/// Maximum decoded gRPC message size to send and receive
pub const RPC_MAX_MESSAGE_SIZE: usize = 1024 * 1024 * 1024; // 1GB

// Generated by prost; clippy 1.98 objects to the size spread of the message
// enum and there is nothing to do about that by hand.
#[allow(clippy::large_enum_variant)]
pub mod protowire {
    tonic::include_proto!("protowire");
}
